### PR TITLE
Resolves #35

### LINKED ISSUE #35: Success or failure response
# Brief

When the backend server finishes processing the request it will end in either failure or success.  If it fails it should show a pop up that informs the user.
# minimum requirements
- Success Pop Up
  - Tells the user "Successfully submitted Snack for review"
  - Pop up Button says "OK"
- Failure Pop Up
  - Tells the user "There was a problem processing your snack. Please try again later."
  - Pop up Button says "OK"
- Duplication issue Pop Up
  - Tells the user "This snack already exists"
  - pop up button says "OK"
- When pop up buttons are selected the pop up should be dismissed.

```
//  RMSPopUp.swift

func successPopUpOn(vc: UIViewController, complete: () -> ()) {
   let popup = UIAlertController()

   vc.presentViewController(popup, animated: true) {

   }
}

func failPopUpOn(vc: UIViewController, complete: () -> ()) {

}

func duplicationPopUpOn(vc: UIViewController, complete: () -> ()) {

}


```

### PR DESCRIPTION
**Pull request by Iceyhan**
Pull Request

### CODE REVIEW

**Comment by Iceyhan** [comment]
@wh1pch81n Ello, Code review please :)

**Comment by wh1pch81n** [comment]
@Iceyhan  ok I'll review it in one minute

**Comment by Iceyhan** [comment]
@wh1pch81n  Will do. Would you like me to push the update after?

**Comment by wh1pch81n** [comment]
@Iceyhan  yeah.  Make the changes on your local branch.  Run one more time to verify it still works.  Then push it to sh35

**Pull request merged**
